const res = {
  success: true,
  data: {
    updateInfo: '北京时间 23:21:34',
    totalBoxUnitInfo: '万',
    splitTotalBox: '8984.0',
    serverTimestamp: 1571239294000,
    crystal: {
      maoyanViewInfo: '100.0',
      status: 1,
      viewInfo: '260.4',
      viewUnitInfo: '万张',
    },
    totalBoxInfo: '9586.4',
    list: [
      {
        avgSeatView: '5.4%',
        avgShowView: '9',
        avgViewBox: '37.0',
        boxInfo: '3042.12',
        boxRate: '31.7%',
        movieId: 1230121,
        movieName: '中国机长',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映17天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '38.2%',
        showInfo: '101299',
        showRate: '32.2%',
        splitAvgViewBox: '34.4',
        splitBoxInfo: '2827.17',
        splitBoxRate: '31.4%',
        splitSumBoxInfo: '23.44亿',
        sumBoxInfo: '25.32亿',
        viewInfo: '82.0',
        viewInfoV2: '82.0万',
      },
      {
        avgSeatView: '8.9%',
        avgShowView: '12',
        avgViewBox: '36.6',
        boxInfo: '2959.55',
        boxRate: '30.8%',
        movieId: 1277939,
        movieName: '我和我的祖国',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映17天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '22.8%',
        showInfo: '71493',
        showRate: '22.7%',
        splitAvgViewBox: '35.1',
        splitBoxInfo: '2836.17',
        splitBoxRate: '31.5%',
        splitSumBoxInfo: '24.99亿',
        sumBoxInfo: '26.60亿',
        viewInfo: '80.6',
        viewInfoV2: '80.6万',
      },
      {
        avgSeatView: '6.7%',
        avgShowView: '8',
        avgViewBox: '36.6',
        boxInfo: '2094.32',
        boxRate: '21.8%',
        movieId: 342146,
        movieName: '犯罪现场',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映5天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '21.5%',
        showInfo: '72650',
        showRate: '23.1%',
        splitAvgViewBox: '33.7',
        splitBoxInfo: '1929.66',
        splitBoxRate: '21.4%',
        splitSumBoxInfo: '1.61亿',
        sumBoxInfo: '1.74亿',
        viewInfo: '57.1',
        viewInfoV2: '57.1万',
      },
      {
        avgSeatView: '5.3%',
        avgShowView: '6',
        avgViewBox: '38.1',
        boxInfo: '959.13',
        boxRate: '10.0%',
        movieId: 1250700,
        movieName: '攀登者',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映17天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '11.8%',
        showInfo: '46215',
        showRate: '14.7%',
        splitAvgViewBox: '35.8',
        splitBoxInfo: '901.61',
        splitBoxRate: '10.0%',
        splitSumBoxInfo: '9.41亿',
        sumBoxInfo: '10.12亿',
        viewInfo: '25.1',
        viewInfoV2: '25.1万',
      },
      {
        avgSeatView: '11.7%',
        avgShowView: '13',
        avgViewBox: '32.7',
        boxInfo: '233.29',
        boxRate: '2.4%',
        movieId: 1251174,
        movieName: '打过长江去',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映首日',
        releaseInfoColor: '#FF9900 1.00',
        seatRate: '1.5%',
        showInfo: '5642',
        showRate: '1.7%',
        splitAvgViewBox: '29.1',
        splitBoxInfo: '207.11',
        splitBoxRate: '2.3%',
        splitSumBoxInfo: '207.1万',
        sumBoxInfo: '233.2万',
        viewInfo: '7.1',
        viewInfoV2: '7.1万',
      },
      {
        avgSeatView: '43.0%',
        avgShowView: '56',
        avgViewBox: '36.7',
        boxInfo: '106.59',
        boxRate: '1.1%',
        movieId: 1277982,
        movieName: '决胜时刻',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映27天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '0.1%',
        showInfo: '524',
        showRate: '0.1%',
        splitAvgViewBox: '35.8',
        splitBoxInfo: '103.75',
        splitBoxRate: '1.1%',
        splitSumBoxInfo: '1.08亿',
        sumBoxInfo: '1.11亿',
        viewInfo: '2.8',
        viewInfoV2: '2.8万',
      },
      {
        avgSeatView: '1.7%',
        avgShowView: '2',
        avgViewBox: '32.8',
        boxInfo: '31.07',
        boxRate: '0.3%',
        movieId: 1219701,
        movieName: '急速逃脱',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映5天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '1.3%',
        showInfo: '5855',
        showRate: '1.8%',
        splitAvgViewBox: '30.0',
        splitBoxInfo: '28.46',
        splitBoxRate: '0.3%',
        splitSumBoxInfo: '373.3万',
        sumBoxInfo: '403.7万',
        viewInfo: '0.9',
        viewInfoV2: '9459',
      },
      {
        avgSeatView: '2.4%',
        avgShowView: '3',
        avgViewBox: '33.3',
        boxInfo: '31.05',
        boxRate: '0.3%',
        movieId: 1225993,
        movieName: '雪人奇缘',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映16天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '0.9%',
        showInfo: '4139',
        showRate: '1.3%',
        splitAvgViewBox: '30.8',
        splitBoxInfo: '28.70',
        splitBoxRate: '0.3%',
        splitSumBoxInfo: '9350.4万',
        sumBoxInfo: '1.00亿',
        viewInfo: '0.9',
        viewInfoV2: '9308',
      },
      {
        avgSeatView: '21.8%',
        avgShowView: '26',
        avgViewBox: '35.3',
        boxInfo: '9.56',
        boxRate: '<0.1%',
        movieId: 1242130,
        movieName: '古田军号',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映77天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '<0.1%',
        showInfo: '108',
        showRate: '<0.1%',
        splitAvgViewBox: '35.3',
        splitBoxInfo: '9.55',
        splitBoxRate: '0.1%',
        splitSumBoxInfo: '3446.1万',
        sumBoxInfo: '3544.5万',
        viewInfo: '0.2',
        viewInfoV2: '2705',
      },
      {
        avgSeatView: '1.9%',
        avgShowView: '2',
        avgViewBox: '32.9',
        boxInfo: '6.85',
        boxRate: '<0.1%',
        movieId: 1211270,
        movieName: '哪吒之魔童降世',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映83天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '0.2%',
        showInfo: '1275',
        showRate: '0.4%',
        splitAvgViewBox: '30.3',
        splitBoxInfo: '6.31',
        splitBoxRate: '<0.1%',
        splitSumBoxInfo: '45.89亿',
        sumBoxInfo: '49.71亿',
        viewInfo: '0.2',
        viewInfoV2: '2083',
      },
      {
        avgSeatView: '0.7%',
        avgShowView: '1',
        avgViewBox: '29.2',
        boxInfo: '5.50',
        boxRate: '<0.1%',
        movieId: 1178432,
        movieName: '丑娃娃',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映4天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '0.6%',
        showInfo: '2788',
        showRate: '0.8%',
        splitAvgViewBox: '26.6',
        splitBoxInfo: '5.00',
        splitBoxRate: '<0.1%',
        splitSumBoxInfo: '298.0万',
        sumBoxInfo: '330.6万',
        viewInfo: '0.1',
        viewInfoV2: '1881',
      },
      {
        avgSeatView: '1.8%',
        avgShowView: '2',
        avgViewBox: '36.9',
        boxInfo: '2.65',
        boxRate: '<0.1%',
        movieId: 359377,
        movieName: '罗小黑战记',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映40天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '<0.1%',
        showInfo: '472',
        showRate: '0.1%',
        splitAvgViewBox: '33.4',
        splitBoxInfo: '2.40',
        splitBoxRate: '<0.1%',
        splitSumBoxInfo: '2.85亿',
        sumBoxInfo: '3.13亿',
        viewInfo: '0.0',
        viewInfoV2: '720',
      },
      {
        avgSeatView: '2.1%',
        avgShowView: '2',
        avgViewBox: '33.9',
        boxInfo: '2.29',
        boxRate: '<0.1%',
        movieId: 1260354,
        movieName: '亲密旅行',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映14天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '<0.1%',
        showInfo: '355',
        showRate: '0.1%',
        splitAvgViewBox: '31.8',
        splitBoxInfo: '2.15',
        splitBoxRate: '<0.1%',
        splitSumBoxInfo: '306.0万',
        sumBoxInfo: '335.3万',
        viewInfo: '0.0',
        viewInfoV2: '677',
      },
      {
        avgSeatView: '14.3%',
        avgShowView: '32',
        avgViewBox: '32.6',
        boxInfo: '1.45',
        boxRate: '<0.1%',
        movieId: 1284333,
        movieName: '樵夫·廖俊波',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映41天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '<0.1%',
        showInfo: '14',
        showRate: '<0.1%',
        splitAvgViewBox: '30.0',
        splitBoxInfo: '1.34',
        splitBoxRate: '<0.1%',
        splitSumBoxInfo: '80.1万',
        sumBoxInfo: '87.4万',
        viewInfo: '0.0',
        viewInfoV2: '447',
      },
      {
        avgSeatView: '43.2%',
        avgShowView: '39',
        avgViewBox: '34.5',
        boxInfo: '1.45',
        boxRate: '<0.1%',
        movieId: 1256872,
        movieName: '为国而歌',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '点映',
        releaseInfoColor: '#FF9900 1.00',
        seatRate: '<0.1%',
        showInfo: '11',
        showRate: '<0.1%',
        splitAvgViewBox: '32.0',
        splitBoxInfo: '1.35',
        splitBoxRate: '<0.1%',
        splitSumBoxInfo: '7.8万',
        sumBoxInfo: '8.2万',
        viewInfo: '0.0',
        viewInfoV2: '422',
      },
      {
        avgSeatView: '14.4%',
        avgShowView: '13',
        avgViewBox: '41.3',
        boxInfo: '1.28',
        boxRate: '<0.1%',
        movieId: 1298696,
        movieName: '零零后',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映44天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '<0.1%',
        showInfo: '24',
        showRate: '<0.1%',
        splitAvgViewBox: '39.0',
        splitBoxInfo: '1.21',
        splitBoxRate: '<0.1%',
        splitSumBoxInfo: '359.7万',
        sumBoxInfo: '371.4万',
        viewInfo: '0.0',
        viewInfoV2: '310',
      },
      {
        avgSeatView: '2.3%',
        avgShowView: '2',
        avgViewBox: '27.6',
        boxInfo: '0.91',
        boxRate: '<0.1%',
        movieId: 1245196,
        movieName: '友情以上',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映27天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '<0.1%',
        showInfo: '191',
        showRate: '<0.1%',
        splitAvgViewBox: '24.7',
        splitBoxInfo: '0.82',
        splitBoxRate: '<0.1%',
        splitSumBoxInfo: '4677.4万',
        sumBoxInfo: '5217.0万',
        viewInfo: '0.0',
        viewInfoV2: '332',
      },
      {
        avgSeatView: '2.1%',
        avgShowView: '2',
        avgViewBox: '35.7',
        boxInfo: '0.83',
        boxRate: '<0.1%',
        movieId: 1215605,
        movieName: '速度与激情：特别行动',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映55天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '<0.1%',
        showInfo: '145',
        showRate: '<0.1%',
        splitAvgViewBox: '32.5',
        splitBoxInfo: '0.75',
        splitBoxRate: '<0.1%',
        splitSumBoxInfo: '13.17亿',
        sumBoxInfo: '14.29亿',
        viewInfo: '0.0',
        viewInfoV2: '233',
      },
      {
        avgSeatView: '22.3%',
        avgShowView: '40',
        avgViewBox: '33.7',
        boxInfo: '0.80',
        boxRate: '<0.1%',
        movieId: 1285674,
        movieName: '桂香街',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '重映27天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '<0.1%',
        showInfo: '6',
        showRate: '<0.1%',
        splitAvgViewBox: '33.7',
        splitBoxInfo: '0.80',
        splitBoxRate: '<0.1%',
        splitSumBoxInfo: '1055.0万',
        sumBoxInfo: '1055.5万',
        viewInfo: '0.0',
        viewInfoV2: '239',
      },
      {
        avgSeatView: '3.3%',
        avgShowView: '4',
        avgViewBox: '27.5',
        boxInfo: '0.71',
        boxRate: '<0.1%',
        movieId: 1263074,
        movieName: '红星照耀中国',
        myRefundNumInfo: '--',
        myRefundRateInfo: '--',
        onlineBoxRate: '--',
        refundViewInfo: '--',
        refundViewRate: '--',
        releaseInfo: '上映70天',
        releaseInfoColor: '#666666 1.00',
        seatRate: '<0.1%',
        showInfo: '78',
        showRate: '<0.1%',
        splitAvgViewBox: '27.1',
        splitBoxInfo: '0.70',
        splitBoxRate: '<0.1%',
        splitSumBoxInfo: '2905.4万',
        sumBoxInfo: '2943.7万',
        viewInfo: '0.0',
        viewInfoV2: '259',
      },
    ],
    totalBoxUnit: '万',
    totalBox: '9586.4',
    splitTotalBoxUnit: '万',
    queryDate: '2019-10-16',
    serverTime: '2019-10-16 23:21:34',
    splitTotalBoxUnitInfo: '万',
    splitTotalBoxInfo: '8984.0',
  },
};
